/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/visites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir"];
        put: operations["mettreAJour"];
        post?: never;
        delete: operations["supprimer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_1"];
        put: operations["mettreAJour_1"];
        post?: never;
        delete: operations["supprimer_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_2"];
        put: operations["mettreAJour_2"];
        post?: never;
        delete: operations["supprimer_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ruches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_3"];
        put: operations["mettreAJour_3"];
        post?: never;
        delete: operations["supprimer_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plannings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_4"];
        put: operations["mettreAJour_4"];
        post?: never;
        delete: operations["supprimer_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_5"];
        put: operations["mettreAJour_5"];
        post?: never;
        delete: operations["supprimer_5"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fermiers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_6"];
        put: operations["mettreAJour_6"];
        post?: never;
        delete: operations["supprimer_6"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fermes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_7"];
        put: operations["mettreAJour_7"];
        post?: never;
        delete: operations["supprimer_7"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_8"];
        put: operations["mettreAJour_8"];
        post?: never;
        delete: operations["supprimer_8"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister"];
        put?: never;
        post: operations["creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visites/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listerPhotos"];
        put?: never;
        post: operations["ajouterPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_1"];
        put?: never;
        post: operations["creer_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_2"];
        put?: never;
        post: operations["creer_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ruches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_3"];
        put?: never;
        post: operations["creer_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["historique"];
        put?: never;
        post: operations["enregistrer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recoltes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_4"];
        put?: never;
        post: operations["creer_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plannings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_5"];
        put?: never;
        post: operations["creer_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plannings/{id}/refuser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refuser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plannings/{id}/approuver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approuver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mesures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["serie"];
        put?: never;
        post: operations["ingerer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_6"];
        put?: never;
        post: operations["creer_6"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fermiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_7"];
        put?: never;
        post: operations["creer_7"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fermes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_8"];
        put?: never;
        post: operations["creer_8"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_9"];
        put?: never;
        post: operations["creer_9"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visites/{id}/rapport.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rapportPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taches/rappels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rappels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tableaux/synthese": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["synthese"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tableaux/production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["production"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tableaux/previsions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["previsions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tableaux/calendrier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["calendrier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tableaux/alertes-sanitaires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["alertesSanitaires"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{id}/voisins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["voisins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/proches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["proches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/grappes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["grappes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/getZummHoneyActualQuantity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * getZummHoneyActualQuantity
         * @description Quantité de miel actuelle d'une ruche (ou du rucher entier), dans l'unité demandée.
         */
        get: operations["getZummHoneyActualQuantity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recoltes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenir_9"];
        put?: never;
        post?: never;
        delete: operations["supprimer_9"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recoltes/tracabilite/{lot}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tracer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plannings/tournee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tournee"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meteo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pourSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mesures/journalier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["serieJournaliere"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mesures/alertes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["alertesOuvertes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lots/{id}/mention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/visites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["visites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/ruches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ruches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["convertir"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuration/seuils": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["seuils"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_10"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detecter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visites/{id}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["supprimerPhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["supprimer_10"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VisiteCorps: {
            /** Format: int64 */
            rucheId: number;
            /** Format: int64 */
            agentId: number;
            /** Format: int64 */
            planningId?: number;
            /** Format: date */
            dateVisite: string;
            /**
             * Format: time
             * @example 14:30:00
             */
            heureVisite?: string;
            /** Format: int32 */
            dureeMin?: number;
            /** @enum {string} */
            raison?: "controle" | "recolte" | "traitement" | "nourrissage" | "division" | "autre";
            constatations?: string;
            actionsPrevues?: string;
            actionsEffectuees?: string;
            recommandations?: string;
            /** @enum {string} */
            effectifQualitatif?: "faible" | "moyen" | "fort";
            /** @enum {string} */
            etatSante?: "bon" | "moyen" | "mauvais";
            /** Format: int32 */
            productivite?: number;
        };
        PhotoReponse: {
            /** Format: int64 */
            id?: number;
            url?: string;
            legende?: string;
            /** Format: date-time */
            creeLe?: string;
        };
        VisiteReponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            /** Format: int64 */
            agentId?: number;
            agentNom?: string;
            /** Format: int64 */
            planningId?: number;
            /** Format: date */
            dateVisite?: string;
            /**
             * Format: time
             * @example 14:30:00
             */
            heureVisite?: string;
            /** Format: int32 */
            dureeMin?: number;
            /** @enum {string} */
            raison?: "controle" | "recolte" | "traitement" | "nourrissage" | "division" | "autre";
            constatations?: string;
            actionsPrevues?: string;
            actionsEffectuees?: string;
            recommandations?: string;
            /** @enum {string} */
            effectifQualitatif?: "faible" | "moyen" | "fort";
            /** @enum {string} */
            etatSante?: "bon" | "moyen" | "mauvais";
            /** Format: int32 */
            productivite?: number;
            photos?: components["schemas"]["PhotoReponse"][];
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        TacheCorps: {
            libelle: string;
            /** Format: int64 */
            rucheId?: number;
            /** Format: int64 */
            agentId?: number;
            /** Format: date */
            echeance?: string;
            faite?: boolean;
        };
        TacheReponse: {
            /** Format: int64 */
            id?: number;
            libelle?: string;
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            /** Format: int64 */
            agentId?: number;
            agentNom?: string;
            /** Format: date */
            echeance?: string;
            faite?: boolean;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        SiteCorps: {
            nom: string;
            /** Format: int64 */
            fermeId: number;
            latitude: number;
            longitude: number;
            altitude?: number;
            /** Format: date */
            dateMiseEnOeuvre: string;
            /** Format: date */
            dateDemenagement?: string;
            /** Format: date */
            dateCloture?: string;
        };
        SiteReponse: {
            /** Format: int64 */
            id?: number;
            nom?: string;
            /** Format: int64 */
            fermeId?: number;
            fermeNom?: string;
            latitude?: number;
            longitude?: number;
            altitude?: number;
            /** Format: date */
            dateMiseEnOeuvre?: string;
            /** Format: date */
            dateDemenagement?: string;
            /** Format: date */
            dateCloture?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        CompartimentCorps: {
            /** @enum {string} */
            type: "corps" | "hausse";
            /** Format: int32 */
            nbCadres?: number;
        };
        RucheCorps: {
            modele: string;
            /** Format: int64 */
            siteId: number;
            /** Format: int64 */
            fermeId: number;
            /** Format: int64 */
            agentResponsableId?: number;
            /** @enum {string} */
            etat?: "creee" | "peuplee" | "active" | "en_division" | "en_collecte" | "cloturee";
            compartiments: components["schemas"]["CompartimentCorps"][];
        };
        CompartimentReponse: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: "corps" | "hausse";
            /** Format: int32 */
            nbCadres?: number;
        };
        RucheReponse: {
            /** Format: int64 */
            id?: number;
            modele?: string;
            /** Format: int64 */
            siteId?: number;
            siteNom?: string;
            /** Format: int64 */
            fermeId?: number;
            fermeNom?: string;
            /** Format: int64 */
            agentResponsableId?: number;
            agentResponsableNom?: string;
            /** @enum {string} */
            etat?: "creee" | "peuplee" | "active" | "en_division" | "en_collecte" | "cloturee";
            /** Format: int32 */
            nbHausses?: number;
            compartiments?: components["schemas"]["CompartimentReponse"][];
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        PlanningCorps: {
            /** Format: int64 */
            rucheId: number;
            /** Format: int64 */
            agentId: number;
            /** Format: int64 */
            superviseurId?: number;
            /** Format: date */
            datePrevue: string;
            /**
             * Format: time
             * @example 14:30:00
             */
            heurePrevue?: string;
            /** Format: int32 */
            dureeMin?: number;
            /** @enum {string} */
            raison?: "controle" | "recolte" | "traitement" | "nourrissage" | "division" | "autre";
        };
        PlanningReponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            /** Format: int64 */
            agentId?: number;
            agentNom?: string;
            /** Format: int64 */
            superviseurId?: number;
            superviseurNom?: string;
            /** Format: date */
            datePrevue?: string;
            /**
             * Format: time
             * @example 14:30:00
             */
            heurePrevue?: string;
            /** Format: int32 */
            dureeMin?: number;
            /** @enum {string} */
            raison?: "controle" | "recolte" | "traitement" | "nourrissage" | "division" | "autre";
            /** @enum {string} */
            statut?: "propose" | "approuve" | "refuse";
            motifRefus?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        LotCorps: {
            reference: string;
            /** Format: date */
            dateConditionnement: string;
            quantiteKg: number;
            typeMiel?: string;
            note?: string;
            origines: components["schemas"]["OrigineDeclaree"][];
        };
        OrigineDeclaree: {
            /** Format: int64 */
            recolteId?: number;
            paysOrigine: string;
            pourcentage: number;
        };
        LotReponse: {
            /** Format: int64 */
            id?: number;
            reference?: string;
            /** Format: date */
            dateConditionnement?: string;
            quantiteKg?: number;
            typeMiel?: string;
            note?: string;
            composition?: components["schemas"]["PartReponse"][];
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        PartReponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            recolteId?: number;
            recolteLot?: string;
            paysOrigine?: string;
            pourcentage?: number;
        };
        FermierCorps: {
            nom: string;
            contact?: string;
        };
        FermierReponse: {
            /** Format: int64 */
            id?: number;
            nom?: string;
            contact?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        FermeCorps: {
            nom: string;
            /** Format: int64 */
            fermierId: number;
        };
        FermeReponse: {
            /** Format: int64 */
            id?: number;
            nom?: string;
            /** Format: int64 */
            fermierId?: number;
            fermierNom?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        AgentCorps: {
            nom: string;
            /** @enum {string} */
            role: "apiculteur" | "superviseur" | "responsable" | "admin";
            /** Format: int64 */
            fermeId?: number;
            email?: string;
        };
        AgentReponse: {
            /** Format: int64 */
            id?: number;
            nom?: string;
            /** @enum {string} */
            role?: "apiculteur" | "superviseur" | "responsable" | "admin";
            /** Format: int64 */
            fermeId?: number;
            fermeNom?: string;
            email?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        PhotoCorps: {
            url: string;
            legende?: string;
        };
        ReineCorps: {
            /** Format: int64 */
            rucheId: number;
            /** Format: date */
            dateEvenement: string;
            statut: string;
            couleurMarquage?: string;
            /** Format: int32 */
            anneeNaissance?: number;
            race?: string;
            note?: string;
        };
        ReineReponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            /** Format: date */
            dateEvenement?: string;
            statut?: string;
            couleurMarquage?: string;
            /** Format: int32 */
            anneeNaissance?: number;
            race?: string;
            note?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        RecolteCorps: {
            /** Format: int64 */
            rucheId: number;
            /** Format: date */
            dateRecolte: string;
            quantiteKg: number;
            typeMiel?: string;
            note?: string;
        };
        RecolteReponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            /** Format: date */
            dateRecolte?: string;
            quantiteKg?: number;
            typeMiel?: string;
            lot?: string;
            note?: string;
            qrPayload?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            majLe?: string;
        };
        DecisionCorps: {
            motif?: string;
        };
        MesureCorps: {
            /** Format: int64 */
            rucheId: number;
            /** @enum {string} */
            typeIndicateur: "poids" | "temperature" | "humidite" | "activite";
            valeur: number;
            /** Format: date-time */
            instant?: string;
        };
        AlerteReponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            /** @enum {string} */
            typeIndicateur?: "poids" | "temperature" | "humidite" | "activite";
            niveau?: string;
            message?: string;
            valeurDeclenchement?: number;
            ouverte?: boolean;
            /** Format: date-time */
            ouverteLe?: string;
            /** Format: date-time */
            fermeeLe?: string;
        };
        MesureReponse: {
            /** Format: int64 */
            rucheId?: number;
            /** @enum {string} */
            typeIndicateur?: "poids" | "temperature" | "humidite" | "activite";
            /** Format: date-time */
            instant?: string;
            valeur?: number;
            alertes?: components["schemas"]["AlerteReponse"][];
        };
        SessionReponse: {
            utilisateur?: string;
            roles?: string[];
            exploitation?: string;
        };
        Roi: {
            valeurProductionEur?: number;
            coutInterventionsEur?: number;
            /** Format: double */
            roiPourcent?: number;
        };
        SyntheseReponse: {
            /** Format: int64 */
            nombreRuches?: number;
            /** Format: int64 */
            nombreVisites?: number;
            visitesParRaison?: {
                [key: string]: number;
            };
            /** Format: double */
            productiviteMoyenne?: number;
            poidsTotalActuelKg?: number;
            /** Format: int64 */
            alertesOuvertes?: number;
            roi?: components["schemas"]["Roi"];
        };
        LigneProduction: {
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            poidsActuelKg?: number;
            poidsMinKg?: number;
            poidsMaxKg?: number;
            /** Format: int64 */
            nombreMesures?: number;
            sousSeuil?: boolean;
            /** Format: double */
            productiviteMoyenne?: number;
        };
        PrevisionRecolte: {
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            poidsActuelKg?: number;
            tendanceKgParJour?: number;
            projection7jKg?: number;
            tendance?: string;
            /** Format: int64 */
            nombreMesures?: number;
        };
        CalendrierCellule: {
            /** Format: int64 */
            agentId?: number;
            agentNom?: string;
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            /** Format: int32 */
            nombreVisites?: number;
            visites?: components["schemas"]["VisiteBreve"][];
        };
        VisiteBreve: {
            /** Format: int64 */
            id?: number;
            /** Format: date */
            date?: string;
            /** @enum {string} */
            raison?: "controle" | "recolte" | "traitement" | "nourrissage" | "division" | "autre";
            /** @enum {string} */
            etatSante?: "bon" | "moyen" | "mauvais";
        };
        AlerteSanitaire: {
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            /** @enum {string} */
            dernierEtatSante?: "bon" | "moyen" | "mauvais";
            /** Format: date */
            derniereVisite?: string;
            /** Format: int64 */
            joursDepuisVisite?: number;
            niveau?: string;
            motif?: string;
        };
        VoisinSite: {
            site?: components["schemas"]["SiteReponse"];
            distanceMetres?: number;
        };
        GrappeSites: {
            /** Format: int32 */
            numero?: number;
            latitudeCentre?: number;
            longitudeCentre?: number;
            /** Format: int32 */
            nombreSites?: number;
            /** Format: int64 */
            nombreRuches?: number;
            sites?: components["schemas"]["SiteReponse"][];
            isolee?: boolean;
        };
        QuantiteMiel: {
            /** Format: int64 */
            rucheId?: number;
            quantite?: number;
            unite?: string;
        };
        TraceReponse: {
            lot?: string;
            /** Format: int64 */
            rucheId?: number;
            rucheModele?: string;
            siteNom?: string;
            fermeNom?: string;
            /** Format: date */
            dateRecolte?: string;
            quantiteKg?: number;
            typeMiel?: string;
        };
        EtapeTournee: {
            /** Format: int32 */
            ordre?: number;
            /** Format: int64 */
            siteId?: number;
            siteNom?: string;
            latitude?: number;
            longitude?: number;
            planningIds?: number[];
            /** Format: int32 */
            nombreVisites?: number;
            distanceDepuisPrecedenteMetres?: number;
        };
        TourneeReponse: {
            /** Format: int64 */
            agentId?: number;
            agentNom?: string;
            /** Format: date */
            date?: string;
            /** Format: int32 */
            nombreSites?: number;
            /** Format: int32 */
            nombreVisites?: number;
            distanceTotaleMetres?: number;
            etapes?: components["schemas"]["EtapeTournee"][];
        };
        MeteoReponse: {
            /** Format: int64 */
            siteId?: number;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** Format: double */
            temperatureCelsius?: number;
            /** Format: int32 */
            humiditePourcent?: number;
            /** Format: double */
            ventKmh?: number;
            source?: string;
            /** Format: date-time */
            instant?: string;
        };
        PointJournalier: {
            /** Format: date-time */
            jour?: string;
            moyenne?: number;
            minimum?: number;
            maximum?: number;
            /** Format: int64 */
            nombre?: number;
        };
        MentionOrigine: {
            texte?: string;
            origines?: components["schemas"]["Part"][];
            melange?: boolean;
        };
        Part: {
            paysOrigine?: string;
            libelle?: string;
            pourcentage?: number;
        };
        Info: {
            nom?: string;
            version?: string;
            accueil?: string;
            langues?: string[];
        };
        Resultat: {
            /** Format: double */
            valeur?: number;
            de?: string;
            vers?: string;
            /** Format: double */
            resultat?: number;
        };
        SeuilsMetier: {
            langueParDefaut?: string;
            languesActives?: string[];
            /** Format: int32 */
            poidsRucheAlerteKg?: number;
            /** Format: int32 */
            temperatureMinCelsius?: number;
            /** Format: int32 */
            temperatureMaxCelsius?: number;
            /** Format: int32 */
            humiditeMaxPourcent?: number;
            /** Format: int32 */
            delaiAlerteJours?: number;
            /** Format: int32 */
            arrondiDegresPublic?: number;
            /** Format: int32 */
            taillePageParDefaut?: number;
            prixMielKgEur?: number;
            coutVisiteEur?: number;
        };
        AuditEntreeReponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            instant?: string;
            acteur?: string;
            action?: string;
            entite?: string;
            /** Format: int64 */
            entiteId?: number;
            resume?: string;
        };
        AnomalieReponse: {
            /** Format: int64 */
            rucheId?: number;
            /** @enum {string} */
            typeIndicateur?: "poids" | "temperature" | "humidite" | "activite";
            /** Format: double */
            alpha?: number;
            /** Format: double */
            seuilZ?: number;
            /** Format: double */
            baseline?: number;
            /** Format: double */
            ecartType?: number;
            /** Format: int32 */
            nombrePoints?: number;
            anomalies?: components["schemas"]["PointAnomalie"][];
        };
        PointAnomalie: {
            /** Format: date-time */
            instant?: string;
            valeur?: number;
            /** Format: double */
            zScore?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    obtenir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VisiteReponse"];
                };
            };
        };
    };
    mettreAJour: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisiteCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VisiteReponse"];
                };
            };
        };
    };
    supprimer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenir_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TacheReponse"];
                };
            };
        };
    };
    mettreAJour_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TacheCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TacheReponse"];
                };
            };
        };
    };
    supprimer_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenir_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SiteReponse"];
                };
            };
        };
    };
    mettreAJour_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SiteReponse"];
                };
            };
        };
    };
    supprimer_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenir_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RucheReponse"];
                };
            };
        };
    };
    mettreAJour_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RucheCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RucheReponse"];
                };
            };
        };
    };
    supprimer_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenir_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanningReponse"];
                };
            };
        };
    };
    mettreAJour_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanningCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanningReponse"];
                };
            };
        };
    };
    supprimer_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenir_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LotReponse"];
                };
            };
        };
    };
    mettreAJour_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LotCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LotReponse"];
                };
            };
        };
    };
    supprimer_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenir_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FermierReponse"];
                };
            };
        };
    };
    mettreAJour_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FermierCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FermierReponse"];
                };
            };
        };
    };
    supprimer_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenir_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FermeReponse"];
                };
            };
        };
    };
    mettreAJour_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FermeCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FermeReponse"];
                };
            };
        };
    };
    supprimer_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenir_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentReponse"];
                };
            };
        };
    };
    mettreAJour_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentReponse"];
                };
            };
        };
    };
    supprimer_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VisiteReponse"][];
                };
            };
        };
    };
    creer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisiteCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VisiteReponse"];
                };
            };
        };
    };
    listerPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PhotoReponse"][];
                };
            };
        };
    };
    ajouterPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PhotoReponse"];
                };
            };
        };
    };
    lister_1: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
                tri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TacheReponse"][];
                };
            };
        };
    };
    creer_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TacheCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TacheReponse"];
                };
            };
        };
    };
    lister_2: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
                tri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SiteReponse"][];
                };
            };
        };
    };
    creer_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SiteReponse"];
                };
            };
        };
    };
    lister_3: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
                tri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RucheReponse"][];
                };
            };
        };
    };
    creer_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RucheCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RucheReponse"];
                };
            };
        };
    };
    historique: {
        parameters: {
            query: {
                rucheId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReineReponse"][];
                };
            };
        };
    };
    enregistrer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReineCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReineReponse"];
                };
            };
        };
    };
    lister_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecolteReponse"][];
                };
            };
        };
    };
    creer_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecolteCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecolteReponse"];
                };
            };
        };
    };
    lister_5: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
                tri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanningReponse"][];
                };
            };
        };
    };
    creer_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanningCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanningReponse"];
                };
            };
        };
    };
    refuser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanningReponse"];
                };
            };
        };
    };
    approuver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanningReponse"];
                };
            };
        };
    };
    serie: {
        parameters: {
            query: {
                rucheId: number;
                type: "poids" | "temperature" | "humidite" | "activite";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MesureReponse"][];
                };
            };
        };
    };
    ingerer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MesureCorps"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MesureReponse"];
                };
            };
        };
    };
    lister_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LotReponse"][];
                };
            };
        };
    };
    creer_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LotCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LotReponse"];
                };
            };
        };
    };
    lister_7: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
                tri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FermierReponse"][];
                };
            };
        };
    };
    creer_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FermierCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FermierReponse"];
                };
            };
        };
    };
    lister_8: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
                tri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FermeReponse"][];
                };
            };
        };
    };
    creer_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FermeCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FermeReponse"];
                };
            };
        };
    };
    lister_9: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
                tri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentReponse"][];
                };
            };
        };
    };
    creer_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCorps"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentReponse"];
                };
            };
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionReponse"];
                };
            };
        };
    };
    rapportPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    rappels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TacheReponse"][];
                };
            };
        };
    };
    synthese: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyntheseReponse"];
                };
            };
        };
    };
    production: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LigneProduction"][];
                };
            };
        };
    };
    previsions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrevisionRecolte"][];
                };
            };
        };
    };
    calendrier: {
        parameters: {
            query: {
                debut: string;
                fin: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalendrierCellule"][];
                };
            };
        };
    };
    alertesSanitaires: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlerteSanitaire"][];
                };
            };
        };
    };
    voisins: {
        parameters: {
            query?: {
                limite?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoisinSite"][];
                };
            };
        };
    };
    proches: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                rayonMetres?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SiteReponse"][];
                };
            };
        };
    };
    grappes: {
        parameters: {
            query?: {
                distanceMetres?: number;
                minimumSites?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GrappeSites"][];
                };
            };
        };
    };
    getZummHoneyActualQuantity: {
        parameters: {
            query?: {
                /** @description Ruche ciblée ; omis = total du rucher */
                rucheId?: number;
                /** @description Unité de masse (kg par défaut) : mg, g, kg, t, lb */
                unite?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuantiteMiel"];
                };
            };
        };
    };
    obtenir_9: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecolteReponse"];
                };
            };
        };
    };
    supprimer_9: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tracer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TraceReponse"];
                };
            };
        };
    };
    tournee: {
        parameters: {
            query: {
                agentId: number;
                date: string;
                departSiteId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TourneeReponse"];
                };
            };
        };
    };
    pourSite: {
        parameters: {
            query: {
                siteId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeteoReponse"];
                };
            };
        };
    };
    serieJournaliere: {
        parameters: {
            query: {
                rucheId: number;
                type: "poids" | "temperature" | "humidite" | "activite";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PointJournalier"][];
                };
            };
        };
    };
    alertesOuvertes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlerteReponse"][];
                };
            };
        };
    };
    mention: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MentionOrigine"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Info"];
                };
            };
        };
    };
    visites: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    ruches: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    convertir: {
        parameters: {
            query: {
                valeur: number;
                de: string;
                vers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Resultat"];
                };
            };
        };
    };
    seuils: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeuilsMetier"];
                };
            };
        };
    };
    lister_10: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditEntreeReponse"][];
                };
            };
        };
    };
    detecter: {
        parameters: {
            query: {
                rucheId: number;
                type: "poids" | "temperature" | "humidite" | "activite";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnomalieReponse"];
                };
            };
        };
    };
    supprimerPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                photoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    supprimer_10: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
